name: Pharoh Kernel Apollo
run-name: Pharoh Kernel Apollo

on:
  push:
    branches: [ staging ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nexgang/ubuntu:latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Kernel Apollo
        run: sudo apt-get update -y && bash clone.sh && cd kernel/ && bash kbuild.sh apollo null
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
